# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97b564a89626f393ead960527e2b0d66f895bea4055e4212c6a16d6697a0d4bbee7aa77f9d5a81a534b01df126892b84ef955c18fde552dc5b19b1dc7557805a

test:
  secret_key_base: ad6ec63c131ba8a374c8ad170020d1ccd3fcf9e77430fef28bdfdfe83902d6fe576ba32e2404a0b85f2b199b92926593b46a6f7b61fd5c334e455bfde17842e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
